### ISSUE TITLE
[Bug]: Multiple API Keys for users not working

### ISSUE THREAD

**Issue by ItzJustSamu** [FyreHost/FyreBot-issues#4]
### What happened?

So basically I set an API for myself and made new API keys with both read and write permissions and even with the other users setting /settoken only the the first person who added api key can use the bot

NO ERRORS IN LOG FOR THIS ONE

https://user-images.githubusercontent.com/45722897/152882091-787f2a54-6ea9-4922-a5e1-a5beeae3286a.png

3.0.7

### Version

1.0.2 (Default)

### What setup are you seeing the bug on?

Pterodactyl (FyreBot Egg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrxbox98** [comment]
For /start you need a user api key not an application one
